# Generated by Django 6.0.7 on 2026-07-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('Contact Us', 'Contact Us'), ('Enquire Now', 'Enquire Now'), ('Request Demo', 'Request Demo')], default='Contact Us', max_length=30),
        ),
    ]
